### ISSUE TITLE
Update the validate_data function to handle excel/CSV files

### ISSUE THREAD

**Issue by yulric** [Big-Life-Lab/PHES-ODM-Validation#148] opened 2023-02-28 15:33 UTC
The behavior of the `validate_data` needs to be updated to handle the case where the data argument comes from a CSV/Excel file. This need comes from MECP. The current behavior changes are:

* Don't show coercion warnings when converting a string to a date or a number
* The row numbers in the error reports should match up with the CSV/Excel sheet

**Comment by zargot** [comment] 2023-02-28 16:49
duplicate of #143

**Comment by zargot** [comment] 2023-02-28 18:23
The user is expecting that excel types are transferred to python instead of going through string coercion. We may want to implement that, but at the same time we're doing fine with our normal string coercion as long as we don't log them as warnings when validating spreadsheets, so let's go with that for now. 👍

**Comment by yulric** [comment] 2023-02-28 18:43
Not sure I understand, how would we "transfer" a type from excel to Python? Do you mean just checking the type of a column in excel and then coercing it to that type in the code?

**Comment by zargot** [comment] 2023-02-28 18:53
if the excel type is integer then it doesn't make sense to log a coercion warning from string to int, since the user already has it as integer, but I guess we're not able to convert the data directly without going through string in any case, so my point is moot. :)

**Closed** 2023-04-12 00:13 UTC
Labels: enhancement
